config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'index#home'

  devise_for :users

  resources :users, only: [:show]
  resources :posts
  resources :commentaries, only: [:create]

  get 'search', to: 'search#search', as: 'search'

  post 'like', to: 'likes#like', as: 'like'
  post 'unlike', to: 'likes#unlike', as: 'unlike'

  post 'follow', to: 'follow#follow_user', as: 'follow_user'
  post 'unfollow', to: 'follow#unfollow_user', as: 'unfollow_user'
  get 'follows', to: 'follow#index', as: 'index_follow_user'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commentary.rb
# frozen_string_literal: true

class Commentary < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :post_id, presence: true
  validates :user_id, presence: true
  validates :commentary_text, presence: true, length: { maximum: 200 }
end

app/models/follow.rb
# frozen_string_literal: true

class Follow < ActiveRecord::Base
  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    update_attribute(:blocked, true)
  end
end

app/models/image_uploader.rb
# frozen_string_literal: true

require 'image_processing/mini_magick'

class ImageUploader < Shrine
  plugin :validation_helpers
  plugin :determine_mime_type

  Attacher.validate do
    validate_extension %w[jpg jpeg png WEBP]
  end
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include ImageUploader[:image]
  belongs_to :user
  has_many :commentary
  has_many :likes, dependent: :destroy

  validates :image, presence: true
  validates :title, presence: true, length: { maximum: 100 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include ImageUploader[:image]
  include PgSearch::Model
  pg_search_scope :find_by_name,
                  against: :name,
                  using: {
                    tsearch: { prefix: true }
                  }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :commentary, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true # , uniqueness: true

  acts_as_followable
  acts_as_follower
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_account_update_params, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name image])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name image])
  end

  private

  def redirect_if_not_log_in
    redirect_to root_path unless user_signed_in?
  end
end

app/controllers/follow_controller.rb
# frozen_string_literal: true

class FollowController < ApplicationController
  include(FollowHelper)
  before_action :user_signed_in?
  before_action :redirect_if_not_log_in
  before_action :create_manager
  def index
    @following = @manager.get_followings.paginate(page: params[:page], per_page: 10)
    @followers = @manager.get_followers
  end

  def follow_user
    if @manager.follow(params[:follow_id])
      flash[:success] = 'You have followed'
      basic_redirect
    end
  end

  def unfollow_user
    if @manager.unfollow(params[:unfollow_id])
      flash[:success] = 'You have unfollowed'
      basic_redirect
    end
  end

  private

  def create_manager
    @manager = FollowManager.new(current_user)
  end
end

app/controllers/index_controller.rb
# frozen_string_literal: true

class IndexController < ApplicationController
  def home
    @posts = Post.where(user_id: current_user.id) if user_signed_in?
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  include(FollowHelper) # it allows to to basic_redirect that means redirect to page which send response
  before_action :user_signed_in?
  before_action :create_manager

  def like
    if @like_manager.put_like
      flash[:success] = 'You like it'
      basic_redirect
    end
  end

  def unlike
    if @like_manager.put_unlike
      basic_redirect
      flash[:danger] = 'You have disliked it'
    end
  end

  private

  def like_params
    params.permit(:user_id, :post_id)
  end

  def create_manager
    @like_manager = LikeManager.new(like_params)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :user_signed_in?
  before_action :redirect_if_not_log_in
  before_action :create_editor

  def index
    @posts = @post_editor.index(current_user).paginate(page: params[:page], per_page: 10)
  end

  def show
    @post = @post_editor.show
  end

  def edit
    @post = @post_editor.show
    unless current_user.id == @post.user_id
      redirect_to root_path
      flash[:alert] = 'Do not try to edit not yours posts!'
    end
  end

  def update
    if @post_editor.update(post_params)
      flash[:success] = 'Post was updated'
      redirect_to root_path
    else
      flash[:danger] = 'Post didnt update'
      redirect_to root_path
    end
  end

  def new
    @post = Post.new
  end

  def create
    if PostCreator.new(post_params, current_user).create_post
      flash[:success] = 'Post created'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def destroy
    @post_editor.destroy
    flash[:success] = 'Post deleted'
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :image, :comment)
  end

  def create_editor
    @post_editor = PostEditor.new(params[:id])
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  before_action :user_signed_in?
  before_action :redirect_if_not_log_in

  def search
    @searched_users = SearchManager.new(params[:name]).call
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :user_signed_in?
  before_action :redirect_if_not_log_in
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)

    redirect_to root_path if @user.id == current_user.id
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def ten_random_users
    ignoring_ids = []
    ignoring_ids.push(current_user.id)
    @preset = current_user.following_users
    @preset.each do |u|
      ignoring_ids.push(u.id)
    end
    offset = User.where.not(id: ignoring_ids).order('RANDOM()').limit(11)
    return offset
  end
end

app/helpers/commentaries_helper.rb
# frozen_string_literal: true

module CommentariesHelper
end

app/helpers/follow_helper.rb
# frozen_string_literal: true

module FollowHelper
  def basic_redirect
    redirect_to request.referer
  end
end

app/helpers/index_helper.rb
# frozen_string_literal: true

module IndexHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
  def post_already_liked(post)
    aim = Like.find_by(post_id: post.id, user_id: current_user.id)

    if aim
      false
    else
      true
    end
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def total_likes(post)
    total_likes = Like.where(post_id: post.id).count
  end
end

app/views/index/home.html.erb
<div class="content mt-5">    
  <% if user_signed_in? %>
    <div class="container mb-5">
      <div class="row">
        <% if current_user.image_data? %>
          <div class="col-4 center">
            <div class="avatar-wrapper-home">
              <%= image_tag current_user.image_url, :class => "avatar-home" %>
            </div>
          </div>
        <% else %>
        <div class="avatar-wrapper-home">
          <%= image_tag 'https://yt3.ggpht.com/a/AATXAJxWoGLwn5Ktx_lNqmI_-BpiAhyiTHctP2U1gw=s900-c-k-c0xffffffff-no-rj-mo', :class => "avatar-home" %>
        </div>
        <% end %>
        <div class="col-8 center">
          <div class="container">
            <div class="row">
              <div class="col-6 center mb-5">
                <span class="font-28">@<%= current_user.name %></span>
              </div>
              <div class="col-6 center mb-5">
                <%= link_to "Settings", edit_user_registration_path, class: "btn btn-outline-secondary font-22 w100" %>
              </div>
            </div>
            <div class="row">
              <div class="col-6 center">
                <span class="font-22"><%= @posts.count%> 
                <% if @posts.count == 1 %>
                  Post
                <% else %>
                  Posts
                <% end %>
                </span>
              </div>
              <div class="col-6 center">
                <span class="font-22 mr-2"><%= current_user.follow_count %> <%= link_to "Followings", index_follow_user_path %></span>
                <span class="font-22"><%= current_user.followers_count%> <%= link_to "Followers", index_follow_user_path %></span>
              </div>            
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container mt-5 border-top">
      <div class="row mt-5">
        <% @posts.each do |p| %>
          <% if p.image_data? %>   
            <div class="col-4 home-feed-wrapper mb-5">
              <%= link_to (image_tag p.image_url, class: "img-home-post"), p %> 
            </div>
          <% end %>
        <% end %>
        <div class="col-4"></div>
        <div class="col-4"></div>
      </div>
    </div>

        <!-- if not signed in -->
  <% else %>
    <h1>Welcome to Eggorkegramm</h1>
    <p>Please Log in or signup before using this awesome app</p>
  <% end %>
</div>
    

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light custom-nav sticky-top">
  <%= link_to "EggorkeGramm", root_path, :class => "navbar-brand starter-logo" %>
  <div class="collapse navbar-collapse custom-nav-links">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item center">
          <%= form_tag search_path, :class => "" ,method: :get do %>
            <%= text_field_tag :name, params[:name], placeholder: "Enter name to search" ,:class => ""  %>
            <%= submit_tag "Search", :class => "btn btn-outline-secondary" %>
          <% end %>
        </li>
        <li class="nav-item"><%= link_to "Add post", new_post_path, :class => "nav-link" %></li>
        <li class="nav-item"><%= link_to "Feed", posts_url, :class => "nav-link" %></li>
        <li class="nav-item"><%= link_to 'My account', root_path, :class => "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class => "nav-link" %></li>
        <li class="nav-item"><span class="nav-link user-name">@<%= current_user.name %></span></li>
      <% else %>
        <li class="nav-item"><%= link_to 'Login', new_user_session_path, :class => "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<% if user_signed_in? %>
  <div class="info sticky pt-4">
    <p class="font-22">Random users to Follow: </p>
    <%ten_random_users.each do |u| %>
    <div class="mt-4">
      <% unless u.followed_by?(current_user) %>
        <% unless current_user == u %>
          <div class="container">
            <div class="row">
              <div class="col-6 container">
                <div class="row">
                  <div class="col-3 center">
                    <% if u.image_data? %>
                      <div class="avatar-wrapper-sub">
                        <%= image_tag u.image_url, :class => "avatar-sub" %>
                      </div>
                    <% else %>
                      <div class="avatar-wrapper-sub">
                        <%= image_tag "userimage.png", :class => "avatar-sub" %>
                      </div>
                    <% end %>
                  </div>
                  <div class="col-9 center">
                    <%= link_to u.name, u , :class => "user-link"%>
                  </div>
                </div>
              </div>
              <div class="col-6">
                <%= form_tag follow_user_path, method: :post do %>
                <%= hidden_field_tag :follow_id, u.id %>
                <%= submit_tag "Follow", class: "btn btn-success" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>    
    <% end %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EggorkeGramm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
  </head>

  <body>
    <div class = "main">
      <%= render 'layouts/navbar' %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <div class="main-content">
        <%= yield %>
        <%= render "layouts/sidebar" %>
      </div>
      
    </div>
    
  </body>

</html>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg|%>
    <p><%= msg %></p>
  <% end %>
<% end %>