config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'index#home'

  devise_for :users

  resources :users, only: [:show]
  resources :posts
  resources :commentaries, only: [:create]

  get 'search', to: 'search#search', as: 'search'

  post 'like', to: 'likes#like', as: 'like'
  post 'unlike', to: 'likes#unlike', as: 'unlike'

  post 'follow', to: 'follow#follow_user', as: 'follow_user'
  post 'unfollow', to: 'follow#unfollow_user', as: 'unfollow_user'
  get 'follows', to: 'follow#index', as: 'index_follow_user'
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  include(FollowHelper) # it allows to to basic_redirect that means redirect to page which send response
  before_action :user_signed_in?
  before_action :create_manager

  def like
    if @like_manager.put_like
      flash[:success] = 'You like it'
      basic_redirect
    end
  end

  def unlike
    if @like_manager.put_unlike
      basic_redirect
      flash[:danger] = 'You have disliked it'
    end
  end

  private

  def like_params
    params.permit(:user_id, :post_id)
  end

  def create_manager
    @like_manager = LikeManager.new(like_params)
  end
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
  def post_already_liked(post)
    aim = Like.find_by(post_id: post.id, user_id: current_user.id)

    if aim
      false
    else
      true
    end
  end
end

app/views/likes/_like.html.erb
<%= form_tag like_path, method: :post do %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= hidden_field_tag :post_id, p.id %>
  <%= submit_tag "Like", class: "btn btn-success" %>
<% end %>

app/views/likes/_likes.html.erb
<% if post_already_liked(p) %>
  <%= render 'likes/like', p:p%>
<% else %>
  <%= render 'likes/unlike', p:p%>
<% end %>

app/views/likes/_unlike.html.erb
<%= form_tag unlike_path, method: :post do %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= hidden_field_tag :post_id, p.id %>
  <%= submit_tag "Unlike", class: "btn btn-danger" %>
<% end %>