config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'index#home'

  devise_for :users

  resources :users, only: [:show]
  resources :posts
  resources :commentaries, only: [:create]

  get 'search', to: 'search#search', as: 'search'

  post 'like', to: 'likes#like', as: 'like'
  post 'unlike', to: 'likes#unlike', as: 'unlike'

  post 'follow', to: 'follow#follow_user', as: 'follow_user'
  post 'unfollow', to: 'follow#unfollow_user', as: 'unfollow_user'
  get 'follows', to: 'follow#index', as: 'index_follow_user'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include ImageUploader[:image]
  include PgSearch::Model
  pg_search_scope :find_by_name,
                  against: :name,
                  using: {
                    tsearch: { prefix: true }
                  }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :commentary, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true # , uniqueness: true

  acts_as_followable
  acts_as_follower
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    # devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image_data])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :user_signed_in?
  before_action :redirect_if_not_log_in
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)

    redirect_to root_path if @user.id == current_user.id
  end
end

app/views/users/show.html.erb
<div class="content mt-5">    
  <div class="container mb-5">
    <div class="row">
      <% if @user.image_data? %>
        <div class="col-4 center">
          <div class="avatar-wrapper-home">
            <%= image_tag @user.image_url, :class => "avatar-home" %>
          </div>
        </div>
      <% else %>
      <div class="col-4 center">
        <div class="avatar-wrapper-home">
          <%= image_tag "userimage.png", :class => "avatar-home" %>
        </div>
      </div>
      <% end %>
      <div class="col-8 center">
        <div class="container">
          <div class="row">
            <div class="col-6 center mb-5">
              <span class="font-28">@<%= @user.name %></span>
            </div>
            <div class="col-6 center mb-5"></div>
          </div>
          <div class="row">
            <div class="col-6 center">
              <span class="font-22"><%= @posts.count%> 
              <% if @posts.count == 1 %>
                Post
              <% else %>
                Posts
              <% end %>
              </span>
            </div>
            <div class="col-6 center">
              <% if current_user.following?(@user) %>
                <%= form_tag unfollow_user_path, method: :post do %>
                  <%= hidden_field_tag :unfollow_id, @user.id %>
                  <%= submit_tag "Unfollow", class: "btn btn-danger" %>
                <% end %>
              <% else %>
                <%= form_tag follow_user_path, method: :post do %>
                  <%= hidden_field_tag :follow_id, @user.id %>
                  <%= submit_tag "Follow", class: "btn btn-success" %>
                <% end %>
              <% end %>
            </div>            
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container mt-5 border-top">
    <div class="row mt-5">
      <% @posts.each do |p| %>
        <% if p.image_data? %>   
          <div class="col-4 home-feed-wrapper mb-5">
            <%= link_to (image_tag p.image_url, class: "img-home-post"), p %> 
          </div>
        <% end %>
      <% end %>
      <div class="col-4"></div>
      <div class="col-4"></div>
    </div>
  </div>
</div>
    